### ISSUE TITLE
What we do when vault fails?

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/bosh-lite-deployment#2]
When vault fails to work, `genesis new environment site environment` will save some credential templates in `credentials.yml`, then later we have to manually generate those credentials since vault failed to work when we create new environment.

It will be nice we will be noticed when vault fails to work, so we can fix it before we create new environment and we do not need to manually generate credentials and save them into vault manually.

**Comment by jhunt** [comment]
Fixed in #3
